### ISSUE TITLE
[Bug] Missing tooltips on the Player Info, Ship Info, and Hardpoint Info Panels

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/Endless-Sky-Delta#154]
### Describe the bug

These three panels should have tooltips that pop up when hovering over various statistics. And they don't. Hovering does work in other areas, such as outfitters and shipyard. Just not in these three panels.

### Steps to Reproduce

1. Go to player info panel
2. Mouse over a statistic
3. See error

### Expected Behavior

Tooltips should show up.

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

Endless Sky Delta 0.10.10, 0.10.9, 0.10.8

### Additional Information

I'll be spending a bunch of time trying to solve this, but extra eyes that spot likely looking things would be much appreciated.

My suspicion is that it has something to do with the addition of the hardpoint panel, but I haven't actually narrowed it down specifically to that yet.

**Comment by Zitchas** [comment]
I've dived into the code a bit a few times, and I can't follow the tooltip code. (all code and L references here refer to upstream, not Delta, since Upstream is where it works, and it doesn't work in Delta. Trying to figure out how it works first)

So it is called here in ShipInfoPanel.cpp L133:
```
    // If the player hovers their mouse over a ship attribute, show its tooltip.
    infoDisplay.DrawTooltips();
```

Most places that I see name.function(), I can go find the file called name, and look for the function in it. But there is no infoDisplay.cpp file. 

There are, however, three DrawTooltips() functions in the game:
- ItemInfoDisplay.cpp
- MissionPanel.cpp
- PreferencesPanel.cpp

There is, however, this line in ShipInfoPanel.h, L86
```
	// Information about the currently selected ship.
	ShipInfoDisplay infoDisplay;
	std::map<std::string, std::vector<const Outfit *>> outfits;
```

I don't know what this does. I don't even know if the third line there is related to the line above it, but the line break before and after that set of three lines implies that it is.

Looking at ShipInfoDisplay, there is no function called infoDisplay, nor is there any mention of tooltips anywhere.

Looking in the ItemInfoDisplay.cpp code, L99 where the DrawTooltips function is:
```
void ItemInfoDisplay::DrawTooltips() const
{
	if(!hoverCount || hoverCount-- < HOVER_TIME || !hoverText.Height())
		return;

	Point textSize(hoverText.WrapWidth(), hoverText.Height() - hoverText.ParagraphBreak());
	Point boxSize = textSize + Point(20., 20.);

	Point topLeft = hoverPoint;
	if(topLeft.X() + boxSize.X() > Screen::Right())
		topLeft.X() -= boxSize.X();
	if(topLeft.Y() + boxSize.Y() > Screen::Bottom())
		topLeft.Y() -= boxSize.Y();

	FillShader::Fill(topLeft + .5 * boxSize, boxSize, *GameData::Colors().Get("tooltip background"));
	hoverText.Draw(topLeft + Point(10., 10.), *GameData::Colors().Get("medium"));
}
```

This function refers to a bunch of pieces of information.
- hoverCount
- HOVER_TIME
- hoverText

Going back to ShipInfoDisplay.cpp, there's no mention of any of these three items anywhere in it. 

HOVER_TIME is defined in a bunch of places, including all three of the files that have "DrawTooltips" functions. So that doesn't really narrow anything down. 

hoverText is the most promising, lots of places using it, and is defined in a few places, such as ItemInfoDisplay.h as `	mutable WrappedText hoverText;` but no indication of how text gets *into* it.


If anyone has any feedback on what I'm reading wrong, and/or an explanation of how the game gets the hover text into the hoverText variable, it'd be much appreciated.

**Comment by Zitchas** [comment]
This section looks promising, though:
```
void ItemInfoDisplay::CheckHover(const Table &table, const string &label) const
{
	if(!hasHover)
		return;

	Point distance = hoverPoint - table.GetCenterPoint();
	Point radius = .5 * table.GetRowSize();
	if(abs(distance.X()) < radius.X() && abs(distance.Y()) < radius.Y())
	{
		hoverCount += 2 * (label == hover);
		hover = label;
		if(hoverCount >= HOVER_TIME)
		{
			hoverCount = HOVER_TIME;
			hoverText.Wrap(GameData::Tooltip(label));
		}
	}
}
```

**Comment by Zitchas** [comment]
I'm thinking that last `hoverText.Wrap(GameData::Tooltip(label));` is how the text gets into the hovertext.

**Comment by warp-core** [comment]
I believe the problem is that you are no longer calling "CheckHover" in "ShipInfoDisplay" when drawing the ship information.
It is normally called from "ShipInfoDisplay::DrawAttributes", which it seems you are still using in the shop panels (hence tooltips still working there) but you don't appear to use it in the ship info panel.
"ShipInfoPanel::Draw" should call "ShipInfoPanel::DrawShipStats" which would call "ShipInfoDisplay::DrawAttributes" (which calls an overload of itself) which draws all the details about the ship and also calls "CheckHover" to set if and for how long any of those attributes have been hovered. "DrawTooltips" will later use the data in these fields to determine if and what tooltip to draw.
Instead, "ShipInfoPanel::Draw" no longer calls "ShipInfoPanel::DrawShipStats" or "ShipInfoDisplay::DrawAttributes". It seems like the contents of this method have been copied to various other functions in "ShipInfoDisplay" which "ShipInfoPanel::Draw" calls directly. These methods do not call "CheckHover" (though, "ShipInfoDisplay::DrawShipEnergyHeatStats" does contains a commented out call to "CheckHover", presumably from that code having been copied straight from "ShipInfoDisplay::DrawAttributes)

**Comment by Zitchas** [comment]
Thanks! Uncommenting that line you mentioned got the heat and energy tooltips working again, and that means I've got working stuff to compare to.
